"""introduce calculation deletion (cascade)

Revision ID: 69e303123e16
Revises: 826f73cb69b5
Create Date: 2016-12-20 12:58:24.662678

"""

# revision identifiers, used by Alembic.
revision = '69e303123e16'
down_revision = '826f73cb69b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calculation_basis_set_calculation_id_fkey', 'calculation_basis_set', type_='foreignkey')
    op.create_foreign_key(None, 'calculation_basis_set', 'calculation', ['calculation_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('calculation_pseudopotential_calculation_id_fkey', 'calculation_pseudopotential', type_='foreignkey')
    op.create_foreign_key(None, 'calculation_pseudopotential', 'calculation', ['calculation_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('task2_calculation_id_fkey', 'task2', type_='foreignkey')
    op.create_foreign_key(None, 'task2', 'calculation', ['calculation_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('task2_artifact_task_id_fkey', 'task2_artifact', type_='foreignkey')
    op.create_foreign_key(None, 'task2_artifact', 'task2', ['task_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task2_artifact_task_id_fkey', 'task2_artifact', type_='foreignkey')
    op.create_foreign_key('task2_artifact_task_id_fkey', 'task2_artifact', 'task2', ['task_id'], ['id'])

    op.drop_constraint('task2_calculation_id_fkey', 'task2', type_='foreignkey')
    op.create_foreign_key('task2_calculation_id_fkey', 'task2', 'calculation', ['calculation_id'], ['id'])

    op.drop_constraint('calculation_pseudopotential_calculation_id_fkey', 'calculation_pseudopotential', type_='foreignkey')
    op.create_foreign_key('calculation_pseudopotential_calculation_id_fkey', 'calculation_pseudopotential', 'calculation', ['calculation_id'], ['id'])

    op.drop_constraint('calculation_basis_set_calculation_id_fkey', 'calculation_basis_set', type_='foreignkey')
    op.create_foreign_key('calculation_basis_set_calculation_id_fkey', 'calculation_basis_set', 'calculation', ['calculation_id'], ['id'])
    ### end Alembic commands ###
