"""introduce replaced_by_reference for structure

Revision ID: 77dda2cb3acf
Revises: 8be005b5346b
Create Date: 2017-01-24 09:37:52.052884

"""

# revision identifiers, used by Alembic.
revision = '77dda2cb3acf'
down_revision = '8be005b5346b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structure', sa.Column('replaced_by_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('structure_name_key', 'structure', type_='unique')
    op.create_foreign_key(None, 'structure', 'structure', ['replaced_by_id'], ['id'])
    op.execute(("ALTER TABLE structure ADD EXCLUDE USING btree (name WITH =)"
                " WHERE (structure.replaced_by_id IS NULL) DEFERRABLE INITIALLY DEFERRED"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('structure_replaced_by_id_fkey', 'structure', type_='foreignkey')
    op.drop_constraint('structure_name_excl', 'structure')
    op.create_unique_constraint('structure_name_key', 'structure', ['name'])
    op.drop_column('structure', 'replaced_by_id')
    ### end Alembic commands ###
