"""introduce TaskRuntimeSettings

Revision ID: 8be005b5346b
Revises: 69e303123e16
Create Date: 2017-01-04 18:11:17.477683

"""

# revision identifiers, used by Alembic.
revision = '8be005b5346b'
down_revision = '69e303123e16'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_runtime_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('settings', postgresql.JSONB(), nullable=False),
    sa.Column('machine_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_runtime_settings')
    ### end Alembic commands ###
