"""introduce link between testresult and calculation collections

Revision ID: fe45a2e57d78
Revises: 66322a6bc199
Create Date: 2017-06-20 10:24:37.263095

"""

# revision identifiers, used by Alembic.
revision = 'fe45a2e57d78'
down_revision = '66322a6bc199'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    op.add_column('test_result2_collection', sa.Column('autogenerated_for_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'test_result2_collection', ['autogenerated_for_id'])
    op.create_foreign_key(None, 'test_result2_collection', 'calculation_collection', ['autogenerated_for_id'], ['id'])

    op.execute(("UPDATE test_result2_collection SET autogenerated_for_id = calculation_collection.id"
                " FROM calculation_collection WHERE calculation_collection.name = test_result2_collection.name"))


def downgrade():
    op.drop_constraint('test_result2_collection_autogenerated_for_id_fkey', 'test_result2_collection', type_='foreignkey')
    op.drop_constraint('test_result2_collection_autogenerated_for_id_key', 'test_result2_collection', type_='unique')
    op.drop_column('test_result2_collection', 'autogenerated_for_id')
